FROM python:3.11
WORKDIR /home/app/
COPY ./requirements.txt /home/app/
RUN pip3 install torch torchvision --index-url https://download.pytorch.org/whl/cpu
RUN pip install -r ./requirements.txt
CMD ["bash"]
#CMD ["streamlit", "run", "appsecure_web.py", "--server.address=0.0.0.0"]

#ENV LM_STUDIO_HOST=localhost
#ENV LM_STUDIO_PORT=1234